apiVersion: v1
kind: Service
metadata:
  name: mongos1-service
  labels:
    run: mongos1
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 31514
    protocol: TCP
    name: mongo
  selector:
    run: mongos1
